name: release-drafter
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        id: Draft
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
